version: '3.8'

services:
  admin-auth:
    container_name: admin-auth-container
    volumes:
      - ./node_modules:/usr/app/node_modules
      - ./:/usr/app
    restart: unless-stopped
    working_dir: /usr/app
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - '8080'
    ports:
      - '8080:8080'
      - '9229:9229'
    command: yarn start
